data_structures.html

Minot fixes for Data Structures

Minor fixes

---

meta_programming.html

https://github.com/howtohireme/ruby.fundamental/issues/2

Meta Programming

---

algorithms.html

https://github.com/howtohireme/ruby.fundamental/issues/37

Devdide in several blocks

---

algorithms.html
data_structures.html
design_patterns.html
functional_programming.html
gotchas.html
meta_programming.html
solid_principles.html
threads.html

https://github.com/howtohireme/ruby.fundamental/issues/35

Headers in one style

---

_sass/_base.scss
algorithms.html
css/main.scss
data_structures.html
design_patterns.html
functional_programming.html
gotchas.html
meta_programming.html
solid_principles.html
threads.html

Inline code for descriptions
Fix paragraphs

Styles for inline code

---

_sass/_component.scss
algorithms.html
data_structures.html

https://github.com/howtohireme/ruby.fundamental/issues/32

[#32] Tables for complexity

---

Procfile

For the moment here deploed https://ruby-fundamental.herokuapp.com/

[#16] Fix to start server on heroku

---

.travis.yml
README.md

[#48] Travis

---

Gemfile
Gemfile.lock
_config.yml
robots.txt

https://www.dev-eth0.de/blog/2016/11/13/jekyll_seo.html
https://sounoob.com.br/sitemap-e-robots-no-jekyll/
https://hashedin.com/blog/5-absolute-must-have-jekyll-plugins-if-you-care-about-performance-and-seo/
https://github.com/jekyll/jekyll-sitemap

Added robots.txt

---

Gemfile
Gemfile.lock

Urgent update jekull

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Add contributions docs and templates

[#66] contribution guides

---

README.md

Issue: [#70]
Description:
Add code triage badge
Testing steps:
Check icon in readme
Checklist:

[#70] Codetriage badge

---

_includes/sidebar.html
_includes/sponsors/234x60.html
_includes/sponsors/300x600.html
_includes/sponsors/468x60.html
_includes/sponsors/728x90.html
_pages/algorithms.html
_pages/data_structures.html
_pages/design_patterns.html
_pages/functional_programming.html
_pages/gotchas.html
_pages/index.html
_pages/interview_questions.html
_pages/meta_programming.html
_pages/solid_principles.html
_pages/threads.html
_sass/_base.scss
_sass/_main.scss
_sass/_sponsors.scss
css/main.scss

Issue: [#13]
Description:
Sponsor blocks and Google adv
Testing steps:
Stitch on display in `_sponsors.scss:7`
Checklist:
Screenshots:

[#13] Sponsor blocks

---

_i18n/en.yml
_pages/interview_questions.html

Issue: [#62]
Description:
Add pages to learn interview questions
Checklist:

[#62] Interview links

---

_i18n/en.yml
_includes/github.html
_includes/head.html
_pages/algorithms.html
_pages/data_structures.html
_pages/design_patterns.html
_pages/functional_programming.html
_pages/gotchas.html
_pages/index.html
_pages/interview_questions.html
_pages/meta_programming.html
_pages/ruby_meister.html
_pages/solid_principles.html
_pages/threads.html
_sass/_base.scss

Issue: [#62]
Description:
Add index page
Testing steps:
Load app
Checklist:

[#62] Index page

---

_i18n/en.yml
_pages/design_patterns.html

Issue: [#100]
Description:
Fixed typos
Testing steps:
Grammarly
Checklist:

[#100] Typos

---

Procfile
_config.production.yml
_config.staging.yml
_config.yml
_includes/head.html
_includes/header.html
robots.txt
sitemap.xml

Issue: [#107]
Description:
Add ENVs variables, devise envs settings
Checklist:

[#107] Add envs

---

_config.yml

Issue: [#107]
Description:
Remove shadowed url
Checklist:

[#107] Hotfix

---

404.html
_config.staging.yml
_layouts/404.html
_pages/algorithms.html
_pages/data_structures.html
_pages/design_patterns.html
_pages/functional_programming.html
_pages/gotchas.html
_pages/index.html
_pages/interview_questions.html
_pages/meta_programming.html
_pages/ruby_meister.html
_pages/solid_principles.html
_pages/threads.html
robots.txt
sitemap.xml

Issue: [#71]
Description:
Add sitemap.xml for better indexation
Testing steps:
go to /sitemap.xml
Checklist:

[#71] Sitemap

---

_config.production.yml
_config.staging.yml

Issue: [#105]
Description:
Forgotten configs
Checklist:

[#105] Hotfixes

---

_includes/counters.html
_includes/head.html

Issue: [#77]
Description:
Add google analitycs
Checklist:

[#77] Google tools

---

README.md

Issue: [#<ID>]
Description:
Fix display travis build status icon
Testing steps:
Checklist:
Screenshots:

Fix display travis build status icon

---

README.md

Issue: [Hotfix]
Description:
Fix badges
Checklist:

[Hotfix] Fix badges after rename

---

CNAME

Issue: [#137]
Description:
Remove for avoid problems

[#137] Remove cname

---

sitemap.xml

Issue: [#127]
Description:
Add localized parts for sitemap.xml
Checklist:

[#127] Update sitemap.xml

---

_config.production.yml
_config.staging.yml
_config.yml
_includes/head.html
_includes/header.html
_includes/sidebar.html

Issue: [#128]
Description:
Add attributes and full path for improving international SEO
Checklist:

[#128] International seo for links

---

_config.production.yml
_config.staging.yml
_config.yml

Issue: [#140]
Description:
Remove useless files
Checklist:

[#140] Remove useless files from translations

---

_config.production.yml
_config.staging.yml
_config.yml
_includes/header.html
_includes/locales.html
_includes/sidebar.html
_sass/_base.scss
javascripts/main.js

Issue: [#126]
Description:
Rework select locales tp select tag
Checklist:

[#126] Select for localization

---

Gemfile
Gemfile.lock
_config.production.yml
_config.staging.yml
_config.yml

To reduce response time
Issue: [#146]
Description:
Add jekyll-gzip to reduce response time.
Testing steps:
Reproduce on my local machine using nginx
Checklist:
Screenshots:

[#146] Add plugin jekyll-gzip

---

.htaccess
_config.production.yml
_config.staging.yml
_config.yml
_includes/data_structure_complexity_header.html
_includes/head.html
_includes/locales.html
_pages/index.html

[#145] Rewrite url

---

.gitignore
.provision/certificates.yml
.provision/templates/nginx.conf
README.md
Rakefile
_includes/github.html
_includes/head.html

Issue: [#149 ]
Add adsense
Checklist:

[#149] Adsense

---

_pages/algorithms.html
_pages/data_structures.html
_pages/design_patterns.html
_pages/gotchas.html
_pages/solid_principles.html
_pages/threads.html
_sass/_sponsors.scss

Issue: [#150]
Remove sponsor blocks
Checklist:
Screenshots:

Remove sponsor blocks

---

_includes/head.html

[#151] Adsense

---

_i18n/en.yml

Issue: [#<ID>]
Description:There was a typo error in file "en.yml" ,corrected typo error
Write description here
Testing steps:
Checklist:
Screenshots:

In "en.yml"  line 74 corrected typo error in responsibility

---

_i18n/pt.yml
pt.yml

Issue: [#182 ]
Description:
All corrected
Testing steps:
Checklist:
Screenshots:

182 pt locale

---

_i18n/es.yml

Issue: [#173]
Description:
Hi! I have corrected some writing and consistency errors. There are still more errors to correct.
Checklist:

[#173] es locale and fix typos

---

_i18n/es.yml

Issue: [#173 ]
Description:
Write description here
Testing steps:
Checklist:
Screenshots:

[#173] Updates

---

_i18n/it.yml

Issue: #177 
Description:
Partially fixed Italian translation, now it’s written in correct Italian until line ~300, due to some personal issues I’ll be unable to finish the translation
Checklist:

[#177] IT locale translation

---

_i18n/de.yml

Issue: [#171]
Description:
Wrong translations and grammar typos fixed.

Wrong translations and grammar typos fixed

---

_i18n/tr.yml

Issue: [#<ID>]
Description:  Fixed especially wrongly translated terms such as Threading and Functional Programming. Additionally, there were some sentences with no proper meanings, I fixed them by comparing it with en_locale.
Testing steps:
Checklist:
Screenshots:

Fixed some translation mistakes in tr_locale

---

_i18n/vi.yml

Issue: [#188]
Description:
Fix some typos, and add english name to sort algorithms

Fix some typos, and add english name to sort algorithms

---

_i18n/de.yml

corrected just a few obvious things.

some obvious gammar or typo fixes in de_locale

---

_i18n/fr.yml

Check fr (Français) locale and fix typos
